---
  - name: USE | Detect upstart system
    shell: |
      if [[ `/sbin/init --version` =~ upstart ]]; then echo upstart;
      elif [[ `systemctl` =~ -\.mount ]]; then echo systemd;
      elif [[ -f /etc/init.d/cron && ! -h /etc/init.d/cron ]]; then echo sysv-init;
      else echo UNKNOWN;
      fi
    become: yes
    register: upstart_detect_raw

  - set_fact:
      upstart_system: "{{upstart_detect_raw.stdout}}"
