---
# tasks file for sa-gitlab-ce

  - include: git/main.yml
    when: option_install_git

  - include: go/main.yml
    when: option_install_go

  - include: node/main.yml
    when: option_install_nodejs

  - include: ruby/main.yml
    when: option_install_ruby

  - include: postgres/main.yml
    when: option_install_postgres

  - name: Gitlab | Force restart postgres to apply changes
    service: name="postgresql" state="restarted"
    become: yes
    when: option_install_postgres

  - include: redis/main.yml
    when: option_install_redis

  - name: Gitlab | Force restart redis to apply changes
    service: name="redis-server" state="restarted"
    become: yes
    when: option_install_redis

  - include: nginx/main.yml
    when: option_install_nginx

  - include: tasks_gitlab.yml
